images_path: ""
train_preproc_chunk_path: ""
validation_preproc_chunk_path: ""
test_preproc_chunk_path: ""
train_partiton_path: ""
validation_partiton_path: ""
test_partiton_path: ""
save_eval_logs_path: ""
save_models_path: ""
