---
testing:
 batch_size: 32
 num_workers: 0


model:
 name: 'densenet121' # densenet121, densenet169, densenet201
 num_classes: 5 
 spatial_dims: 3
 n_input_channels: 1 
 pretrained: false
 load_model_path: null # path to pretrained model(and/or optimizer) state dict
 

loss:
 name: 'cross_entropy'

...