---
training:
 batch_size: 32
 num_epochs: 15
 num_workers: 0
 validation_interval: 1 


model:
 name: 'densenet121' # densenet121, densenet169, densenet201
 num_classes: 5 
 spatial_dims: 3
 n_input_channels: 1 
 pretrained: false
 load_model_path: null # path to pretrained model(and/or optimizer) state dict


optimizer:
 name: 'adamw' # adam, adamw, rmsprop
 lr: 0.0001 # # adam, adamw, rmsprop
 weight_decay: 0.00001 # adam, adamw, rmsprop
 betas: [0.9, 0.999] # adam, adamw

loss:
 name: 'cross_entropy'

...