---
training:
 batch_size: 16
 num_epochs: 30
 num_workers: 0
 validation_interval: 1 


model:
 name: 'resnet10' # resnet18, resnet34, resnet50, resnet101 (pretrained models: resnet10p, resnet18p,resnet34p,resnet50p, resnet101p) 
 num_classes: 2
 spatial_dims: 3
 n_input_channels: 1 
 load_model_path: null # path to pretrained model(and/or optimizer) state dict
 dropout_rate_relu: 0.3
 dropout_rate_fc: 0.2


optimizer:
 name: 'adamw' # adam, adamw
 lr: 0.0001 # # adam, adamw
 weight_decay: 0.0001 # adam, adamw, 
 betas: [0.9, 0.999] # adam, adamw


scheduler:
 name: null #'ReduceLROnPlateau'
 factor: 0.5
 patience: 2
 min_lr: 1e-6


loss:
 name: 'cross_entropy_loss' 
 weight: [1, 1] 
 reduction: 'mean'
 label_smoothing: 0.1
 
#  name: 'focal_loss'
#  gamma: 1.5
#  alpha: 0.25
#  reduction: 'mean'
#  weight: [1, 1]
  
...